server:
  port: 9003

spring:
  application:
    name: CUSTOMER-SUBSCRIPTIONS
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/subscriptions
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
  jackson:
    deserialization:
      ACCEPT_SINGLE_VALUE_AS_ARRAY: true
#  zipkin:
#    baseUrl: http://localhost:9411
